module.exports.ls = require("./modules/ls")
module.exports.lsRemote = require("./modules/lsRemote")
module.exports.help = require("./modules/help")
module.exports.install = require("./modules/install")
module.exports.use = require("./modules/use")
module.exports.npm = require("./modules/npm")
